### ISSUE TITLE
nome do repositório

### ISSUE THREAD

**Issue by Andrelamor** [thiagomrm/Violencia-mulheres-SES#11]
@thiagomrm sugiro alterar o nome deste repositório para coincidir com o nome do conjunto publicado [`violencia-mulheres-ses`](https://dados.mg.gov.br/dataset/dados_violencia_mulheres_ses), afinal, já passamos dos testes e vc já fez a primeira atualização mensal, não é mesmo?

**Comment by thiagomrm** [comment]
Repositório renomeado.
